name: CI

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java JDK
        uses: actions/setup-java@v4.0.0
        with:
         java-version: 21
         distribution: 'temurin'
         cache: maven
      
      - name: Build and Test
        run: mvn test
      - name: Upload JaCoCo coverage report as a workflow artifact
        timeout-minutes: 2
        uses: actions/upload-artifact@v3
        path: target/site/jacoco/
        


          
