name: CI

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java JDK
        uses: actions/setup-java@v4.0.0
        with:
         java-version: 21
         distribution: 'temurin'
         cache: maven
      
      - name: Build and Test
        run: mvn test
        
      - name: Upload JaCoCo coverage report as a workflow artifact
        timeout-minutes: 2
        uses: actions/upload-artifact@v3
        with:
         name: jacoco-report
         path: target/site/jacoco/

  mutation-testing:
    name: Mutation Testing
    runs-on: ubuntu-latest
    needs: [ build-and-test ]
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4.0.0
        with:
          java-version: 21
          distribution: 'temurin'
          cache: maven
      - name: Run mutation testing
        run: mvn test-compile org.pitest:pitest-maven:mutationCoverage

  security:
    runs-on: ubuntu-latest
    name: Security Analysis
    needs: [ mutation-testing ] ## TO run the security job, both build and mutation-testing must be completed
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: 21
          distribution: 'temurin'
          cache: maven
      - name: Run OWASP dependency vulnerability check
        run: mvn -B verify --file pom.xml -DskipTests      
   
        


          
